version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: energy-barrier-solver:1.1
    container_name: energy-barrier-solver
    command: python3 main.py
    environment:
      - TZ=America/Indiana/Indianapolis
      - PYTHONUNBUFFERED=1
      - GRAPH_GENERATOR_TYPE=${GRAPH_GENERATOR_TYPE}
      - WITH_PRICE=${WITH_PRICE}
      - NUMBER_OF_PROCESSES=${NUMBER_OF_PROCESSES}
      - RANDOM_DB_NAME=${RANDOM_DB_NAME}
      - INTERSECTION_DB_NAME=${INTERSECTION_DB_NAME}
    volumes:
      - ./db:/app/db
      - ./plan-random.csv:/app/plan-random.csv
      - ./plan-intersection.csv:/app/plan-intersection.csv
    deploy:
      resources:
        limits:
          cpus: "5"
          memory: 20GB
        reservations:
          cpus: "2"
          memory: 2GB